/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var compiled_grammar = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,10],$V1=[1,14],$V2=[1,15],$V3=[1,20],$V4=[1,21],$V5=[1,22],$V6=[1,23],$V7=[7,8],$V8=[7,8,14,25,28,30,31,32,33],$V9=[1,42],$Va=[1,43],$Vb=[1,45],$Vc=[1,46],$Vd=[1,47],$Ve=[1,48],$Vf=[1,49],$Vg=[7,8,14,25,27,28,29,30,31,32,33];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"PROG":3,"ANFANG_PROD":4,"ANFANG_FACTOR":5,"MULTI_INST":6,"EOF":7,"ENDE":8,"SYMBOLE":9,"ANFANG":10,"INST":11,"DECL":12,"PROC":13,"WERT":14,"ID":15,"ASSIGN":16,"DATO":17,"PROC_FARBE":18,"PROC_POS":19,"MOV":20,"MOV_REC":21,"MOV_LIN":22,"MOV_UBE":23,"MOV_UNT":24,"FARBE":25,"(":26,")":27,"POS":28,",":29,"REC":30,"LIN":31,"UBE":32,"UNT":33,"INT":34,"COLOR":35,"ROJO":36,"AZUL":37,"AMARILLO":38,"VERDE":39,"BLANCO":40,"$accept":0,"$end":1},
terminals_: {2:"error",7:"EOF",8:"ENDE",9:"SYMBOLE",10:"ANFANG",14:"WERT",15:"ID",16:"ASSIGN",25:"FARBE",26:"(",27:")",28:"POS",29:",",30:"REC",31:"LIN",32:"UBE",33:"UNT",34:"INT",36:"ROJO",37:"AZUL",38:"AMARILLO",39:"VERDE",40:"BLANCO"},
productions_: [0,[3,2],[3,2],[3,2],[3,2],[4,1],[5,3],[5,1],[5,2],[6,2],[6,1],[11,1],[11,1],[12,4],[13,1],[13,1],[13,1],[20,1],[20,1],[20,1],[20,1],[18,4],[19,6],[21,4],[22,4],[23,4],[24,4],[17,1],[17,1],[17,1],[35,1],[35,1],[35,1],[35,1],[35,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 
        handleBeginAction() 
        if (clearSignal) {
            clearSignal = false
            actionStack.push({action:false, data:[], option:'clear'})
        }
        var stackCopy = actionStack.slice()
        actionStack = []
        return stackCopy
    
break;
case 2:
 
        var isValid = stateInstance.checkAction(Actions.INST)
        if (isValid.error) {
            console.error(isValid.message)
        } 
        var stackCopy = actionStack.slice()
        actionStack = []
        return stackCopy
    
break;
case 3:
 
        var isValid = stateInstance.checkAction(Actions.END)
        if (!isValid.error) {
            stateInstance = new InactiveState()
        } else {
            console.error(isValid.message)
        }
    
break;
case 4:
 console.log(stateInstance.TS) 
break;
case 5:
 
        if (stateInstance.constructor === InactiveState) {
            stateInstance = new ActiveState()
            clearSignal = true
        } else {
            console.error("El programa ya esta iniciado")
        }
    
break;
case 13:

        if (stateInstance.constructor === ActiveState)
            stateInstance.TS[$$[$0-2]] = $$[$0]; // Asignamos DATO.place al ID
    
break;
case 21:

        if (stateInstance.constructor === ActiveState) {            
            if ($$[$0-1].type !== 'c') return console.log("POS debe recibir números como argumento");
            stateInstance.color = cambiarColor($$[$0-1].val);
        }
    
break;
case 22:

        if (stateInstance.constructor === ActiveState) {
            const error1 = validarPosicion($$[$0-3].type, $$[$0-3].val);
            const error2 = validarPosicion($$[$0-1].type, $$[$0-1].val);
            if (error1 || error2) return console.log(error1 || error2);
            var posicionAntigua = stateInstance.cursorPosition;
            stateInstance.cursorPosition = cambiarPosicion($$[$0-3].val, $$[$0-1].val);
        }
    
break;
case 23:

        if (stateInstance.constructor === ActiveState) {
            if ($$[$0-1].type !== 'i') return console.log("POS debe recibir números como argumento");
            var posicionAntigua = stateInstance.cursorPosition;
            stateInstance.cursorPosition = moverRec($$[$0-1].val, stateInstance.cursorPosition);
            actionStack.push({ action: true, data: [stateInstance.color, posicionAntigua, stateInstance.cursorPosition] })
        }
    
break;
case 24:

        if (stateInstance.constructor === ActiveState) {
            if ($$[$0-1].type !== 'i') return console.log("POS debe recibir números como argumento");
            var posicionAntigua = stateInstance.cursorPosition;
            stateInstance.cursorPosition = moverLin($$[$0-1].val, stateInstance.cursorPosition);
            actionStack.push({ action: true, data: [stateInstance.color, posicionAntigua, stateInstance.cursorPosition] })
        }
    
break;
case 25:

        if (stateInstance.constructor !== ActiveState) {
            return; // No hacer nada si no es una instancia activa
        }
        if ($$[$0-1].type !== 'i') return console.log("POS debe recibir números como argumento");
        var posicionAntigua = stateInstance.cursorPosition;
        stateInstance.cursorPosition = moverUbe($$[$0-1].val, stateInstance.cursorPosition);
        actionStack.push({ action: true, data: [stateInstance.color, posicionAntigua, stateInstance.cursorPosition] })
    
break;
case 26:

        if (stateInstance.constructor !== ActiveState) {
            return; // No hacer nada si no es una instancia activa
        }
        if ($$[$0-1].type !== 'i') console.error("POS debe recibir números como argumento");
        else {
            var posicionAntigua = stateInstance.cursorPosition;
            stateInstance.cursorPosition = moverUnt($$[$0-1].val, stateInstance.cursorPosition);
            actionStack.push({ action: true, data: [stateInstance.color, posicionAntigua, stateInstance.cursorPosition] })
        }
    
break;
case 27:

        if (stateInstance.constructor === ActiveState)
            this.$ = stateInstance.TS[$$[$0]] ?? (stateInstance.TS[$$[$0]] = new ElementoTS(null, null))
    
break;
case 28:
this.$ = new ElementoTS('i', Number($$[$0]))
break;
case 29:
this.$ = new ElementoTS('c', $$[$0])
break;
case 30:
 this.$ = "rojo"; 
break;
case 31:
 this.$ = "azul"; 
break;
case 32:
 this.$ = "amarillo"; 
break;
case 33:
 this.$ = "verde"; 
break;
case 34:
 this.$ = "blanco"; 
break;
}
},
table: [{3:1,4:2,6:3,8:[1,4],9:[1,5],10:[1,6],11:7,12:8,13:9,14:$V0,18:11,19:12,20:13,21:16,22:17,23:18,24:19,25:$V1,28:$V2,30:$V3,31:$V4,32:$V5,33:$V6},{1:[3]},{5:24,6:25,7:[1,26],11:7,12:8,13:9,14:$V0,18:11,19:12,20:13,21:16,22:17,23:18,24:19,25:$V1,28:$V2,30:$V3,31:$V4,32:$V5,33:$V6},{7:[1,27]},{7:[1,28]},{7:[1,29]},o([7,14,25,28,30,31,32,33],[2,5]),o($V7,[2,10],{11:7,12:8,13:9,18:11,19:12,20:13,21:16,22:17,23:18,24:19,6:30,14:$V0,25:$V1,28:$V2,30:$V3,31:$V4,32:$V5,33:$V6}),o($V8,[2,11]),o($V8,[2,12]),{15:[1,31]},o($V8,[2,14]),o($V8,[2,15]),o($V8,[2,16]),{26:[1,32]},{26:[1,33]},o($V8,[2,17]),o($V8,[2,18]),o($V8,[2,19]),o($V8,[2,20]),{26:[1,34]},{26:[1,35]},{26:[1,36]},{26:[1,37]},{1:[2,1]},{7:[1,39],8:[1,38]},{1:[2,7]},{1:[2,2]},{1:[2,3]},{1:[2,4]},o($V7,[2,9]),{16:[1,40]},{15:$V9,17:41,34:$Va,35:44,36:$Vb,37:$Vc,38:$Vd,39:$Ve,40:$Vf},{15:$V9,17:50,34:$Va,35:44,36:$Vb,37:$Vc,38:$Vd,39:$Ve,40:$Vf},{15:$V9,17:51,34:$Va,35:44,36:$Vb,37:$Vc,38:$Vd,39:$Ve,40:$Vf},{15:$V9,17:52,34:$Va,35:44,36:$Vb,37:$Vc,38:$Vd,39:$Ve,40:$Vf},{15:$V9,17:53,34:$Va,35:44,36:$Vb,37:$Vc,38:$Vd,39:$Ve,40:$Vf},{15:$V9,17:54,34:$Va,35:44,36:$Vb,37:$Vc,38:$Vd,39:$Ve,40:$Vf},{7:[1,55]},{1:[2,8]},{15:$V9,17:56,34:$Va,35:44,36:$Vb,37:$Vc,38:$Vd,39:$Ve,40:$Vf},{27:[1,57]},o($Vg,[2,27]),o($Vg,[2,28]),o($Vg,[2,29]),o($Vg,[2,30]),o($Vg,[2,31]),o($Vg,[2,32]),o($Vg,[2,33]),o($Vg,[2,34]),{29:[1,58]},{27:[1,59]},{27:[1,60]},{27:[1,61]},{27:[1,62]},{1:[2,6]},o($V8,[2,13]),o($V8,[2,21]),{15:$V9,17:63,34:$Va,35:44,36:$Vb,37:$Vc,38:$Vd,39:$Ve,40:$Vf},o($V8,[2,23]),o($V8,[2,24]),o($V8,[2,25]),o($V8,[2,26]),{27:[1,64]},o($V8,[2,22])],
defaultActions: {24:[2,1],26:[2,7],27:[2,2],28:[2,3],29:[2,4],39:[2,8],55:[2,6]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
    
/* Definiciones */
const { 
    validarPosicion, 
    cambiarColor, 
    cambiarPosicion, 
    moverRec, 
    moverLin, 
    moverUbe, 
    moverUnt
} = require('../src/instrucciones.js')
const { Actions } = require('../src/StateHandler/ActionEnum.js')
const { ElementoTS } = require('../src/StateHandler/ElementoTS.js')
const { ActiveState } = require('../src/StateHandler/ActiveState.js')
const { InactiveState } = require('../src/StateHandler/InactiveState.js')

function handleBeginAction() {
    const isValid = stateInstance.checkAction(Actions.BEGIN).message
    if (isValid.error) console.error(isValid.message)
}

let stateInstance = new InactiveState()
let clearSignal = false
let actionStack = []



/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* Ignorar espacios en blanco */
break;
case 1:return 10;
break;
case 2:return 8;
break;
case 3:return 14;
break;
case 4:return 9;
break;
case 5:return 16;
break;
case 6: yylval = { val: Number(yy_.yytext) }; return 34; 
break;
case 7:return 25;
break;
case 8:return 28;
break;
case 9:return 30;
break;
case 10:return 31;
break;
case 11:return 32;
break;
case 12:return 33;
break;
case 13:return 36;
break;
case 14:return 37;
break;
case 15:return 38;
break;
case 16:return 39;
break;
case 17:return 40;
break;
case 18:return 15; // Identificadores genéricos
break;
case 19:return 26;
break;
case 20:return 27;
break;
case 21:return 29;
break;
case 22:return 7;
break;
}
},
rules: [/^(?:\s+)/,/^(?:anfang\b)/,/^(?:ende\b)/,/^(?:wert\b)/,/^(?:symbole\b)/,/^(?:=)/,/^(?:[0-9]+)/,/^(?:farbe\b)/,/^(?:pos\b)/,/^(?:rec\b)/,/^(?:lin\b)/,/^(?:ube\b)/,/^(?:unt\b)/,/^(?:rojo\b)/,/^(?:azul\b)/,/^(?:amarillo\b)/,/^(?:verde\b)/,/^(?:blanco\b)/,/^(?:[A-Z][0-9])/,/^(?:\()/,/^(?:\))/,/^(?:,)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = compiled_grammar;
exports.Parser = compiled_grammar.Parser;
exports.parse = function () { return compiled_grammar.parse.apply(compiled_grammar, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}